name: Create Pull Request
on:
  workflow_dispatch:

jobs:
  create-pr:
    uses: actions/versions-package-tools/.github/workflows/create-pr-to-update-manifest.yml@dependabot/github_actions/actions/upload-artifact-7  
    with:
      tool-name: "go"
    secrets: inherit